package day12;

import java.util.Scanner;

public class Exception02 {

	public static void main(String[] args) {
		//num1, num2, 연산자 입력하여 메서드 실행 
		// 메서드 호출할때 예외처리
		// 두 수를 입력받고, 연산자를 입력받아 
		
		Scanner scan = new Scanner(System.in);
		System.out.println("숫자와 연산자를 입력");
		int num1 = scan.nextInt();
		int num2 = scan.nextInt();
		String p1 = scan.next();
	
		
		number(num1, num2, p1);
		
	}

	//기능 :사칙연산의 결과를 리턴하는 메서드 생성
	
	public static void number(int num1, int num2, String p1) {
		double res = 0;
		
		try {
			
			switch(p1) {
			case "+":
				int sum = num1 + num2;
				System.out.println(sum);
				break;
			case "-":
				int minus = num1 - num2;
				System.out.println(minus);
				break;
			case "*":
				int mul = num1 * num2;
				System.out.println(mul);
				break;
			case "/":
				double na = (double)num1 / num2;
				System.out.println(na);
				break;
			default:
				break; 
			}
			
		} catch (Exception e) {
			System.out.println("0으로 나누었습니다. exception 발생!!!!");

		}
		System.out.println("종료");

		
		
	}
	
	
}
